# Generated by Django 4.0.6 on 2022-07-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('au_id', models.IntegerField(primary_key=True, serialize=False)),
                ('au_tl', models.CharField(max_length=250)),
                ('au_ar', models.CharField(max_length=250)),
                ('au_sh', models.CharField(max_length=50)),
                ('sh_ar', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('date_ar', models.CharField(max_length=50)),
                ('cit', models.TextField()),
                ('bio', models.TextField()),
                ('bio_ar', models.TextField()),
                ('books', models.TextField()),
                ('books_ar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_tl', models.CharField(max_length=250)),
                ('title_ar', models.CharField(max_length=250)),
                ('pg_len', models.IntegerField()),
                ('pg_rng', models.CharField(max_length=25)),
                ('word_len', models.IntegerField()),
                ('descr', models.TextField()),
                ('descr_ar', models.TextField()),
                ('editions', models.TextField()),
                ('perm', models.TextField()),
                ('permbib', models.TextField()),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('avail_read', models.BooleanField()),
                ('source', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('au_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_corpus.author')),
                ('gen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_corpus.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pg_num', models.IntegerField()),
                ('pg_cont', models.TextField()),
                ('pg_count', models.IntegerField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_corpus.text')),
            ],
        ),
    ]
