# Generated by Django 4.0.6 on 2022-07-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio_ar',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books_ar',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_ar',
        ),
        migrations.RemoveField(
            model_name='text',
            name='descr_ar',
        ),
    ]
