# Generated by Django 4.0.6 on 2022-07-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0003_rename_editions_text_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='added_by',
        ),
    ]
