# Generated by Django 4.0.6 on 2022-08-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0004_remove_text_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='incrp',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
