# Generated by Django 4.0.6 on 2022-08-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0005_author_incrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='incrp',
            field=models.IntegerField(),
        ),
    ]
