# Generated by Django 4.0.6 on 2022-08-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0006_alter_author_incrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='gen_id',
        ),
        migrations.AddField(
            model_name='text',
            name='genre',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='topic',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
