# Generated by Django 4.0.6 on 2022-08-03 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0008_remove_text_added_remove_text_au_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='au_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='text_corpus.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='avail_read',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='descr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='genre',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='pdf',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='perm',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='permbib',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='pg_len',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='pg_rng',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='title_ar',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='title_tl',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='topic',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='word_len',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
