# Generated by Django 4.0.6 on 2022-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0011_text_added_text_au_id_text_avail_read_text_descr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='topic',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='text',
            name='avail_read',
        ),
        migrations.AddField(
            model_name='text',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
