# Generated by Django 4.0.6 on 2022-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0013_remove_text_added_remove_text_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='gen_en',
        ),
        migrations.AddField(
            model_name='genre',
            name='gen_ar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
