# Generated by Django 4.0.6 on 2022-08-10 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0014_rename_genre_genre_gen_en_genre_gen_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_corpus.genre'),
        ),
    ]
