# Generated by Django 4.1.1 on 2022-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0015_alter_text_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='contrib',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
