# Generated by Django 4.0.6 on 2022-10-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_corpus', '0017_text_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='coins',
            new_name='meta',
        ),
    ]
