# Generated by Django 4.0.6 on 2022-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusup',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
