# Generated by Django 4.0.6 on 2022-09-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_corpus', '0003_teammem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMem',
        ),
    ]
