# Generated by Django 4.0.6 on 2022-09-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_corpus', '0005_teammem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammem',
            old_name='mbio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='teammem',
            old_name='mname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teammem',
            old_name='mphoto',
            new_name='photo',
        ),
    ]
