# Generated by Django 4.1.5 on 2023-10-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_corpus', '0007_teammem_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammem',
            name='role',
            field=models.CharField(default='role', max_length=40),
            preserve_default=False,
        ),
    ]
